import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../models/mobile_models.dart';
import '../services/api_client.dart';
import '../services/document_viewer_service.dart';
import '../theme/dalvo_theme.dart';
import '../widgets/dalvo_widgets.dart';
import 'document_assignment_page.dart';
import 'module_common.dart';

class PurchasesPage extends StatefulWidget { const PurchasesPage({super.key}); @override State<PurchasesPage> createState()=>_PurchasesPageState(); }
class _PurchasesPageState extends State<PurchasesPage>{
  final _search=TextEditingController(); String _status=''; bool _loading=true; String? _error; List<Map<String,dynamic>> _rows=const[];
  @override void initState(){super.initState();_load();} @override void dispose(){_search.dispose();super.dispose();}
  Future<void> _load()async{setState((){_loading=true;_error=null;});try{final rows=await ApiClient.instance.purchases(search:_search.text,status:_status);if(mounted)setState(()=>_rows=rows);}catch(error){if(mounted)setState(()=>_error=error is ApiException?error.message:'No se pudieron cargar las compras.');}finally{if(mounted)setState(()=>_loading=false);}}
  Future<void> _filter()async{final value=await showModalBottomSheet<String>(context:context,builder:(context)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[const ListTile(title:Text('Estatus de compra',style:TextStyle(fontWeight:FontWeight.w900))),for(final item in const['','Borrador','Aprobada','Cancelada'])ListTile(title:Text(item.isEmpty?'Todos':item),trailing:_status==item?const Icon(Icons.check,color:DalvoColors.primary):null,onTap:()=>Navigator.pop(context,item))])));if(value!=null){_status=value;_load();}}
  @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(16,18,16,100),children:[const ModuleHeader(eyebrow:'Compras',title:'Órdenes de compra',subtitle:'Consulta proveedores, partidas, montos y documentación.',icon:Icons.inventory_2_outlined),const SizedBox(height:18),ModuleSearch(controller:_search,hint:'OCP, folio, empresa, proveedor o PO',onSearch:_load,onFilters:_filter,filtersActive:_status.isNotEmpty),const SizedBox(height:14),if(_loading)const Center(child:Padding(padding:EdgeInsets.all(40),child:CircularProgressIndicator()))else if(_error!=null)DalvoEmptyState(icon:Icons.error_outline,title:'No se pudo cargar',message:_error!,error:true,action:OutlinedButton(onPressed:_load,child:const Text('Reintentar')))else if(_rows.isEmpty)const DalvoEmptyState(icon:Icons.search_off,title:'Sin compras',message:'No hay resultados con los filtros seleccionados.')else ..._rows.map((row)=>Padding(padding:const EdgeInsets.only(bottom:10),child:DalvoSurface(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PurchaseDetailPage(orderId:int.tryParse('${row['id']}')??0))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${row['folio']??'Sin OCP'}',style:Theme.of(context).textTheme.titleMedium)),Text(dalvoMoney(row['amount']),style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(height:6),Text('${row['company']??''}',style:const TextStyle(color:DalvoColors.primaryDark,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text('${row['title']??''}',maxLines:2,overflow:TextOverflow.ellipsis),const SizedBox(height:6),Text('Proveedor: ${row['supplier']??'Sin proveedor'}',style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:10),Row(children:[DalvoBadge(label:'${row['status']??''}',foreground:statusColor('${row['status']??''}')),const Spacer(),Text('${row['filesCount']??0} archivos',style:Theme.of(context).textTheme.bodySmall),const Icon(Icons.chevron_right)])]))))]));
}

class PurchaseDetailPage extends StatefulWidget{final int orderId;const PurchaseDetailPage({super.key,required this.orderId});@override State<PurchaseDetailPage> createState()=>_PurchaseDetailPageState();}
class _PurchaseDetailPageState extends State<PurchaseDetailPage>{Map<String,dynamic>? _data;String? _error;@override void initState(){super.initState();_load();}Future<void>_load()async{try{final value=await ApiClient.instance.purchaseDetail(widget.orderId);if(mounted)setState(()=>_data=value);}catch(error){if(mounted)setState(()=>_error=error is ApiException?error.message:'No se pudo cargar la compra.');}}
  @override Widget build(BuildContext context){final purchase=_data?['purchase'] as Map<String,dynamic>?;final items=_data?['items'] as List? ?? const[];final files=_data?['files'] as List? ?? const[];return Scaffold(appBar:AppBar(title:Text('${purchase?['folio']??'Compra'}')),body:_error!=null?Center(child:Text(_error!)):_data==null?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[ModuleHeader(eyebrow:'Compras',title:'${purchase?['folio']??''}',subtitle:'${purchase?['company']??''} · ${purchase?['projectFolio']??''}',icon:Icons.inventory_2_outlined),const SizedBox(height:14),DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[DetailValue(label:'Proyecto',value:'${purchase?['title']??''}'),DetailValue(label:'PO cliente',value:'${purchase?['po']??''}'),DetailValue(label:'Estatus',value:'${purchase?['status']??''}'),const Divider(),_amount('Subtotal',purchase?['subtotal']),_amount('IVA',purchase?['iva']),_amount('Total',purchase?['total'],bold:true)])),const SizedBox(height:12),DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Partidas',style:Theme.of(context).textTheme.titleMedium),const SizedBox(height:8),...items.whereType<Map<String,dynamic>>().map((row)=>ListTile(contentPadding:EdgeInsets.zero,title:Text('${row['description']??''}'),subtitle:Text('${row['supplier']??''} · ${row['quantity']??0}'),trailing:Text(dalvoMoney(row['total']),style:const TextStyle(fontWeight:FontWeight.w800))))])),const SizedBox(height:12),DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Archivos',style:Theme.of(context).textTheme.titleMedium),if(files.isEmpty)const Padding(padding:EdgeInsets.only(top:10),child:Text('Sin archivos cargados')) else ...files.whereType<Map<String,dynamic>>().map((file)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.description_outlined),title:Text('${file['name']??''}'),subtitle:Text('${file['type']??''}'),trailing:IconButton(icon:const Icon(Icons.open_in_new),onPressed:()=>DocumentViewerService.open(context,scope:'PURCHASE',fileId:int.tryParse('${file['id']}')??0))))]))]));}
  Widget _amount(String label,dynamic value,{bool bold=false})=>Padding(padding:const EdgeInsets.symmetric(vertical:5),child:Row(children:[Expanded(child:Text(label,style:TextStyle(fontWeight:bold?FontWeight.w900:FontWeight.w500))),Text(dalvoMoney(value),style:TextStyle(fontWeight:bold?FontWeight.w900:FontWeight.w700))]));
}

class FinanceAccountsPage extends StatefulWidget{final bool receivable;const FinanceAccountsPage({super.key,required this.receivable});@override State<FinanceAccountsPage> createState()=>_FinanceAccountsPageState();}
class _FinanceAccountsPageState extends State<FinanceAccountsPage>{final _search=TextEditingController();String _state='';String _pending='';String _company='';DateTime? _from,_to;bool _loading=true;String? _error;List<FinancialAccount>_rows=const[];
 @override void initState(){super.initState();_load();}@override void dispose(){_search.dispose();super.dispose();}String _iso(DateTime?d)=>d==null?'':'${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';
 Future<void>_load()async{setState((){_loading=true;_error=null;});try{final rows=await ApiClient.instance.financialAccounts(receivable:widget.receivable,search:_search.text,state:_state,pending:_pending,company:_company,from:_iso(_from),to:_iso(_to));if(mounted)setState(()=>_rows=rows);}catch(error){if(mounted)setState(()=>_error=error is ApiException?error.message:'No se pudieron cargar las cuentas.');}finally{if(mounted)setState(()=>_loading=false);}}
 Future<void> _filters() async {
   var state = _state, pending = _pending, company = _company;
   DateTime? from = _from, to = _to;
   await showModalBottomSheet(
     context: context,
     isScrollControlled: true,
     builder: (context) => StatefulBuilder(
       builder: (context, setSheet) => Padding(
         padding: EdgeInsets.fromLTRB(20, 22, 20, 28 + MediaQuery.of(context).viewInsets.bottom),
         child: SingleChildScrollView(
           child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [
             Text('Filtros', style: Theme.of(context).textTheme.titleLarge),
             const SizedBox(height: 14),
             TextFormField(initialValue: company, decoration: const InputDecoration(labelText: 'Empresa'), onChanged: (value) => company = value.trim()),
             const SizedBox(height: 10),
             TextFormField(initialValue: state, decoration: const InputDecoration(labelText: 'Estado'), onChanged: (value) => state = value),
             const SizedBox(height: 10),
             TextFormField(initialValue: pending, decoration: const InputDecoration(labelText: 'Pendiente'), onChanged: (value) => pending = value),
             const SizedBox(height: 10),
             Row(children: [
               Expanded(child: OutlinedButton(onPressed: () async { from = await showDatePicker(context: context, firstDate: DateTime(2020), lastDate: DateTime(2035), initialDate: from ?? DateTime.now()); setSheet(() {}); }, child: Text(from == null ? 'Desde' : dalvoDate(from)))),
               const SizedBox(width: 8),
               Expanded(child: OutlinedButton(onPressed: () async { to = await showDatePicker(context: context, firstDate: DateTime(2020), lastDate: DateTime(2035), initialDate: to ?? DateTime.now()); setSheet(() {}); }, child: Text(to == null ? 'Hasta' : dalvoDate(to)))),
             ]),
             const SizedBox(height: 14),
             Row(children: [
               Expanded(child: OutlinedButton(onPressed: () { state = ''; pending = ''; company = ''; from = null; to = null; setSheet(() {}); }, child: const Text('Limpiar'))),
               const SizedBox(width: 8),
               Expanded(child: FilledButton(onPressed: () { _state = state; _pending = pending; _company = company; _from = from; _to = to; Navigator.pop(context); _load(); }, child: const Text('Aplicar'))),
             ]),
           ]),
         ),
       ),
     ),
   );
 }
 @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(16,18,16,100),children:[ModuleHeader(eyebrow:widget.receivable?'Cuentas por cobrar':'Cuentas por pagar',title:widget.receivable?'Facturación y cobranza':'Pagos a proveedores',subtitle:widget.receivable?'Revisa saldos, documentos y pagos de clientes.':'Revisa facturas, pagos y complementos pendientes.',icon:widget.receivable?Icons.request_page_outlined:Icons.payments_outlined),const SizedBox(height:18),ModuleSearch(controller:_search,hint:'Empresa, cliente, folio, proyecto o PO',onSearch:_load,onFilters:_filters,filtersActive:_state.isNotEmpty||_pending.isNotEmpty||_company.isNotEmpty||_from!=null||_to!=null),const SizedBox(height:14),if(_loading)const Center(child:Padding(padding:EdgeInsets.all(40),child:CircularProgressIndicator()))else if(_error!=null)DalvoEmptyState(icon:Icons.error_outline,title:'No se pudo cargar',message:_error!,error:true,action:OutlinedButton(onPressed:_load,child:const Text('Reintentar')))else if(_rows.isEmpty)const DalvoEmptyState(icon:Icons.search_off,title:'Sin cuentas',message:'No hay cuentas que coincidan con los filtros.')else ..._rows.map((row)=>Padding(padding:const EdgeInsets.only(bottom:10),child:DalvoSurface(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>FinanceDetailPage(receivable:widget.receivable,accountId:row.id))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(row.folio.isEmpty?'Cuenta #${row.id}':row.folio,style:Theme.of(context).textTheme.titleMedium)),Text(dalvoMoney(row.amount),style:const TextStyle(fontWeight:FontWeight.w900))]),const SizedBox(height:6),Text(row.company,style:const TextStyle(color:DalvoColors.primaryDark,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(row.title,maxLines:2,overflow:TextOverflow.ellipsis),if(row.po.isNotEmpty)Text('PO: ${row.po}',style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:10),Row(children:[Expanded(child:DalvoBadge(label:row.pending.isEmpty?row.state:row.pending,foreground:statusColor(row.state))),Text('${row.filesCount} archivos',style:Theme.of(context).textTheme.bodySmall),const Icon(Icons.chevron_right)])]))))]));
}

class FinanceDetailPage extends StatefulWidget{final bool receivable;final int accountId;const FinanceDetailPage({super.key,required this.receivable,required this.accountId});@override State<FinanceDetailPage>createState()=>_FinanceDetailPageState();}
class _FinanceDetailPageState extends State<FinanceDetailPage>{Map<String,dynamic>?_data;String?_error;@override void initState(){super.initState();_load();}Future<void>_load()async{try{final value=await ApiClient.instance.financialDetail(receivable:widget.receivable,accountId:widget.accountId);if(mounted)setState(()=>_data=value);}catch(error){if(mounted)setState(()=>_error=error is ApiException?error.message:'No se pudo cargar la cuenta.');}}
 @override Widget build(BuildContext context){final account=_data?['account']as Map<String,dynamic>?;final files=_data?['files']as List? ?? const[];final payments=_data?['payments']as List? ?? const[];return Scaffold(appBar:AppBar(title:Text(account?['folio']?.toString()??'Cuenta')),body:_error!=null?Center(child:Text(_error!)):_data==null?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[ModuleHeader(eyebrow:widget.receivable?'Cuenta por cobrar':'Cuenta por pagar',title:'${account?['folio']??'Cuenta #${widget.accountId}'}',subtitle:'${account?['company']??''}',icon:widget.receivable?Icons.request_page_outlined:Icons.payments_outlined),const SizedBox(height:14),DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[DetailValue(label:'Proyecto',value:'${account?['title']??''}'),DetailValue(label:'Cliente',value:'${account?['client']??''}'),DetailValue(label:'PO',value:'${account?['po']??''}'),DetailValue(label:'Owner',value:'${account?['owner']??''}'),DetailValue(label:'Estado',value:'${account?['state']??''}'),DetailValue(label:'Pendiente',value:'${account?['pending']??''}'),DetailValue(label:'Días de pago',value:'${account?['paymentDays']??0}'),Text(dalvoMoney(account?['amount']),style:Theme.of(context).textTheme.headlineSmall)])),const SizedBox(height:12),FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>DocumentAssignmentPage(initialScope:widget.receivable?'RECEIVABLE':'PAYABLE',initialTargetId:widget.accountId))),icon:const Icon(Icons.attach_file),label:Text(widget.receivable?'Adjuntar factura, pago o complemento':'Adjuntar factura, pago o complemento')),const SizedBox(height:12),DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Documentos',style:Theme.of(context).textTheme.titleMedium),if(files.isEmpty)const Padding(padding:EdgeInsets.only(top:10),child:Text('Sin documentos'))else ...files.whereType<Map<String,dynamic>>().map((file)=>ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.description_outlined),title:Text('${file['name']??''}'),subtitle:Text('${file['type']??''}'),trailing:IconButton(icon:const Icon(Icons.open_in_new),onPressed:()=>DocumentViewerService.open(context,scope:widget.receivable?'RECEIVABLE':'PAYABLE',fileId:int.tryParse('${file['id']}')??0))))])),if(widget.receivable&&payments.isNotEmpty)...[const SizedBox(height:12),DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Pagos registrados',style:Theme.of(context).textTheme.titleMedium),...payments.whereType<Map<String,dynamic>>().map((payment)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(dalvoMoney(payment['amount'])),subtitle:Text('${payment['reference']??''} · ${dalvoDate(payment['paymentDate'])}')))]))]]));}
}

class TasksPage extends StatefulWidget{const TasksPage({super.key});@override State<TasksPage>createState()=>_TasksPageState();}
class _TasksPageState extends State<TasksPage>{final _search=TextEditingController();String _status='';String _priority='';bool _loading=true;String?_error;List<Map<String,dynamic>>_rows=const[];@override void initState(){super.initState();_load();}@override void dispose(){_search.dispose();super.dispose();}Future<void>_load()async{setState(()=>_loading=true);try{final rows=await ApiClient.instance.tasks(search:_search.text,status:_status,priority:_priority);if(mounted)setState((){_rows=rows;_error=null;});}catch(error){if(mounted)setState(()=>_error=error is ApiException?error.message:'No se pudieron cargar las tareas.');}finally{if(mounted)setState(()=>_loading=false);}}Future<void>_set(int id,String value)async{await ApiClient.instance.updateTaskStatus(id,value);_load();}
 @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(16,18,16,100),children:[const ModuleHeader(eyebrow:'Tareas',title:'Seguimiento de pendientes',subtitle:'Solo se muestran tareas propias o asignadas al usuario.',icon:Icons.task_alt_outlined),const SizedBox(height:18),ModuleSearch(controller:_search,hint:'Título, descripción o seguimiento',onSearch:_load),const SizedBox(height:10),Wrap(spacing:7,children:[for(final value in const['','Pendiente','En proceso','Completada'])ChoiceChip(label:Text(value.isEmpty?'Todas':value),selected:_status==value,onSelected:(_){_status=value;_load();})]),const SizedBox(height:7),Wrap(spacing:7,children:[for(final value in const['','Alta','Media','Baja'])ChoiceChip(label:Text(value.isEmpty?'Toda prioridad':value),selected:_priority==value,onSelected:(_){_priority=value;_load();})]),const SizedBox(height:14),if(_loading)const Center(child:CircularProgressIndicator())else if(_error!=null)DalvoEmptyState(icon:Icons.error_outline,title:'No se pudo cargar',message:_error!,error:true)else if(_rows.isEmpty)const DalvoEmptyState(icon:Icons.task_alt,title:'Sin tareas',message:'No hay tareas con estos filtros.')else ..._rows.map((row)=>Padding(padding:const EdgeInsets.only(bottom:10),child:DalvoSurface(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text('${row['title']??''}',style:Theme.of(context).textTheme.titleMedium)),DalvoBadge(label:'${row['priority']??''}')]),const SizedBox(height:8),Text('${row['description']??''}'),const SizedBox(height:8),Text('Asignada a: ${row['assignedTo']??''}',style:Theme.of(context).textTheme.bodySmall),Text('Fecha límite: ${dalvoDate(row['dueDate'])}',style:Theme.of(context).textTheme.bodySmall),const SizedBox(height:10),DropdownButtonFormField<String>(initialValue:'${row['status']??'Pendiente'}',decoration:const InputDecoration(labelText:'Estatus'),items:const[DropdownMenuItem(value:'Pendiente',child:Text('Pendiente')),DropdownMenuItem(value:'En proceso',child:Text('En proceso')),DropdownMenuItem(value:'Completada',child:Text('Completada'))],onChanged:(value){if(value!=null)_set(int.tryParse('${row['id']}')??0,value);})]))))]));
}

class ExportsPage extends StatelessWidget{const ExportsPage({super.key});Future<void>_open(BuildContext context,String kind)async{try{final uri=await ApiClient.instance.temporaryExportUrl(kind);if(!await launchUrl(uri,mode:LaunchMode.externalApplication))throw const ApiException('No se pudo abrir la exportación.');}catch(error){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(error is ApiException?error.message:'No se pudo exportar.')));}}
 @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.fromLTRB(16,18,16,100),children:[const ModuleHeader(eyebrow:'Exportaciones',title:'Descargar información',subtitle:'Genera archivos CSV respetando los permisos y proyectos asignados.',icon:Icons.file_download_outlined),const SizedBox(height:18),for(final item in const[('payables','Cuentas por pagar',Icons.payments_outlined),('receivables','Cuentas por cobrar',Icons.request_page_outlined),('attendance','Asistencias',Icons.location_on_outlined)])Padding(padding:const EdgeInsets.only(bottom:10),child:DalvoSurface(onTap:()=>_open(context,item.$1),child:Row(children:[DalvoIconTile(icon:item.$3),const SizedBox(width:12),Expanded(child:Text(item.$2,style:Theme.of(context).textTheme.titleMedium)),const Icon(Icons.open_in_new_rounded)])))]);
}
